import './index.css'

export { default as AdminLayout } from '../layouts/adminLayout'
export { default as AdminPage } from './adminPage'
export { default as AdminSignIn } from './adminSignIn'
export { default as ForgotPassword } from './forgotPassword'
export { default as OTPVerifier } from './otpVerifier'
export { default as ResetPassword } from './resetPassword'
export { default as AdminsList } from './adminsList'
export { default as Home } from './pages/home'
export { default as WhoWeAre } from './pages/whoWeAre'
export { default as AwardsAndRecognition } from './pages/awardsAndRecognition'
export { default as CathLab } from './pages/cathLab'
export { default as Pinnacle_Agile } from './pages/pinnacle-agile'
export { default as PremierElitePage } from './pages/premierElite'
export { default as PremierSelectPage } from './pages/premierSelect'
export { default as CareersPage } from './pages/careers'
export { default as ContactUs } from './pages/contactUs'
export { default as ServiceAndSupportPage } from './pages/serviceAndSupport'
export { default as NewsAndArticles } from './pages/newsAndArticles'
